import type { ModuleName } from 'src/config/modules'

const moduleType: ModuleName = 'accounting'

const accountingRoutes = [
  {
    path: '/accounting',
    name: 'accounting-dashboard',
    title: 'Dashboard',
    icon: 'dashboard',
    component: () => import('src/pages/accounting/AccountingDashboard.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Accounting Dashboard' },
    subheader: 'Setup',
  },
  {
    path: '/accounting/coa',
    name: 'chart-of-accounts',
    title: 'Chart of Accounts',
    icon: 'account_tree',
    component: () => import('src/pages/accounting/ChartOfAccounts.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Chart of Accounts' },
  },
  {
    path: '/accounting/budget',
    name: 'budget',
    title: 'Opening Balance',
    icon: 'balance',
    component: () => import('src/pages/accounting/OpeningBalance.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Fiscal Opening Balance' },
  },
  {
    path: '/accounting/budget',
    name: 'budget',
    title: 'Budget',
    icon: 'assured_workload',
    component: () => import('src/pages/accounting/FiscalBudget.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Fiscal Budget' },
    separatorafter: true,
  },
  {
    path: '/accounting/settings',
    name: 'settings',
    title: 'Accounting Settings',
    icon: 'settings',
    component: () => import('src/pages/accounting/AccountingSettings.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Accounting Related Settings' },
    separatorafter: false,
  },
  {
    path: '/accounting/journal',
    name: 'journal-entries',
    title: 'Journal Entry',
    icon: 'edit_note',
    component: () => import('src/pages/accounting/JournalEntries.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Journal Entry' },
    subheader: 'entries',
  },
  {
    path: '/accounting/journal?adjustement=1',
    name: 'adjustement-entries',
    title: 'Adjustment Entry',
    icon: 'wrap_text',
    component: () => import('src/pages/accounting/JournalEntries.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Adjustment Entry' },
  },
  {
    path: '/accounting/receipts',
    name: 'receipts',
    title: 'Receipts (In)',
    icon: 'arrow_back',
    component: () => import('src/pages/accounting/ReceiptsPage.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Receipts (Receivables)' },
  },
  {
    path: '/accounting/payments',
    name: 'payments',
    title: 'Payments (Out)',
    icon: 'arrow_forward',
    component: () => import('src/pages/accounting/PaymentsPage.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Payments (Payable)' },
  },
  {
    path: '/accounting/banktransactions',
    name: 'bank-transactions',
    title: 'Bank Transactions',
    icon: 'home_work',
    component: () => import('src/pages/accounting/BankTransactions.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Bank Transactions' },
  },
  {
    path: '/accounting/reconciliation',
    name: 'reconciliation-entries',
    title: 'Bank Reconciliation',
    icon: 'difference',
    component: () => import('src/pages/accounting/BankReconciliation.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Bank Reconciliation' },
  },
  {
    path: '/accounting/reports/coa',
    name: 'report-coa',
    title: 'Print/Filter COA',
    icon: 'list_alt',
    component: () => import('src/pages/accounting/reports/CoaReport.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Report: Chart of Accounts' },
    subheader: 'Reports',
  },
  {
    path: '/accounting/report/tb',
    name: 'trial-balance',
    title: 'Trial Balance',
    icon: 'balance',
    component: () => import('src/pages/accounting/reports/TrialBalance.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Report: Trail Balance' },
  },
  {
    path: '/accounting/report/ledger',
    name: 'ledger',
    title: 'Ledger',
    icon: 'compare',
    component: () => import('src/pages/accounting/reports/LedgerPage.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Report: Ledger' },
  },
  {
    path: '/accounting/report/balancesheet',
    name: 'balance-sheet',
    title: 'Balance Sheet',
    icon: 'balance',
    component: () => import('src/pages/accounting/reports/BalanceSheet.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Report: balancesheet' },
  },
  {
    path: '/accounting/report/cashflow',
    name: 'cash-flow',
    title: 'Cash Flow',
    icon: 'send_money',
    component: () => import('src/pages/accounting/reports/CashFlow.vue'),
    meta: { requiresAuth: true, module: moduleType, title: 'Report: Ledger' },
  },
]

export default accountingRoutes
